import type { Answers, GeneratedFile } from "../types";
import { pick } from "../types";
import { effectiveProfiles, profileById } from "../data/profiles";
import { depthById } from "../data/depths";
import { ruleById, skilledRules } from "../data/rules";
import { joinSections } from "./text";

/** Génère le README.md racine de l'archive : récapitulatif lisible de la config. */
export function generateReadme(a: Answers, files: GeneratedFile[]): string {
  const fr = a.language === "fr";
  const profiles = effectiveProfiles(a.profiles).map(profileById);
  const profileLabel = profiles
    .map((p) => `${pick(p.label, a.language)} (${pick(p.tagline, a.language)})`)
    .join(", ");
  const depth = depthById(a.depth);

  const title = `# ${a.projectName} - ${fr ? "configuration Claude Code" : "Claude Code configuration"}`;

  const summaryLines = [
    `## ${fr ? "Résumé" : "Summary"}`,
    "",
    `- ${fr ? "Profils" : "Profiles"} : **${profileLabel}**`,
    `- ${fr ? "Profondeur" : "Depth"} : **${pick(depth.label, a.language)}** (${depth.level})`,
    `- ${fr ? "Langue" : "Language"} : ${a.language.toUpperCase()}`,
    `- ${fr ? "Rigueur" : "Rigor"} : ${a.rigor}`,
  ];
  const skilled = skilledRules(a);
  if (skilled.length > 0) {
    summaryLines.push(
      fr
        ? `- Skills procéduraux : ${skilled.length} garde-fou(s) déporté(s) dans \`.claude/skills/\` (chargés à la demande)`
        : `- Procedural skills: ${skilled.length} guardrail(s) offloaded to \`.claude/skills/\` (loaded on demand)`,
    );
  }
  const summary = summaryLines.join("\n");

  const rulesList = a.rules.map((id) => {
    const r = ruleById(id);
    return `- ${pick(r.label, a.language)} - ${pick(r.summary, a.language)}`;
  });
  const rulesBlock = [
    `## ${fr ? "Garde-fous inclus" : "Included guardrails"}`,
    "",
    rulesList.length > 0 ? rulesList.join("\n") : fr ? "_Aucun_" : "_None_",
  ].join("\n");

  const filesBlock = [
    `## ${fr ? "Fichiers" : "Files"}`,
    "",
    ...files.map((f) => `- \`${f.path}\``),
  ].join("\n");

  const next = [
    `## ${fr ? "Étapes suivantes" : "Next steps"}`,
    "",
    fr
      ? "Suivez `INSTALL.md` pour déposer la configuration au bon endroit et l'initialiser dans Claude Code."
      : "Follow `INSTALL.md` to place the configuration and initialize it in Claude Code.",
  ].join("\n");

  const footer = [
    "---",
    "",
    fr
      ? "_Généré par Claude Config Studio. Tout le contenu est sourcé de la doc officielle Claude Code (code.claude.com/docs). Relisez et adaptez avant usage en production._"
      : "_Generated by Claude Config Studio. All content is sourced from the official Claude Code docs (code.claude.com/docs). Review and adapt before production use._",
  ].join("\n");

  return joinSections([title, summary, rulesBlock, filesBlock, next, footer]);
}
